In [1]:
%pip install nltk

Defaulting to user installation because normal site-packages is not writeable
Collecting nltk
  Downloading nltk-3.8.1-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 25.2 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: click in /packages/envs/scicomp/lib/python3.11/site-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /packages/envs/scicomp/lib/python3.11/site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in ./.local/lib/python3.11/site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in /packages/envs/scicomp/lib/python3.11/site-packages (from nltk) (4.64.1)
Installing collected packages: nltk
Successfully installed nltk-3.8.1
Note: you may need to restart the kernel to use updated packages.

In [9]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import TfidfVectorizer

def preprocess_text(text):
    # Text Cleaning
    text = re.sub(r'[^\w\s]', '', text)
    
    # Tokenization
    tokens = word_tokenize(text)
    
    # Stop Word Removal
    stop_words = set(stopwords.words('english'))
    tokens = [token for token in tokens if token.lower() not in stop_words]
    
    # Lemmatization
    lemmatizer = WordNetLemmatizer()
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    
    # Join tokens back to text
    preprocessed_text = ' '.join(tokens)
    
    return preprocessed_text

In [4]:
import pandas as pd
data=pd.read_csv('incidents.csv')

In [7]:
data['description']=data.description.astype('str')

In [16]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /home/smagulu1/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/smagulu1/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/smagulu1/nltk_data...

True

In [17]:
data['preproc']=data['description'].apply(preprocess_text)

In [18]:
data['preproc']

0       Late August 31 2023 crude oil spill occurred P...
1       drug runner sailboat modified operate semisubm...
2       28AUG2023 USCG Sector Puget Sound notified NOA...
3       USCG District 7 established Crisis Action Team...
4       Late Sunday night 27AUG2023 USCG Sector San Fr...
                              ...
4430    1500 June 13 1968 World Glory bound Huelva Spa...
4431    March 7 1968 Greek tank vessel General Colocot...
4432    morning March 3 1968 tanker Ocean Eagle ground...
4433    morning March 18 1967 TV Torrey Canyon ran agr...
4434    Tampico Maru henceforth Tampico left Los Angel...
Name: preproc, Length: 4435, dtype: object

In [20]:
filtered_data = data[(data['threat'] == 'oil') | (data['threat'] == 'chemical')]

In [30]:
data[data['threat'].isnull()]

,id,open_date,name,location,lat,lon,threat,tags,commodity,measure_skim,measure_shore,measure_bio,measure_disperse,measure_burn,max_ptl_release_gallons,posts,description,preproc
1932,8165,2009-12-20,"Leaking Propane Tank; Vashon Island, WA","Vashon Island, WA",47.4375,-122.467778,NaN,NaN,Propane,NaN,NaN,NaN,NaN,NaN,200.0,2,"On December 20, 2009, a concerned citizen in V...",December 20 2009 concerned citizen Vashon Isla...
1956,8134,2009-10-27,"Port Stewart; Yabacoa, Puerto Rico","Yabacoa, Puerto Rico",18.0450,-65.804800,NaN,NaN,HFO,NaN,NaN,NaN,NaN,NaN,0.0,12,"On October 27, 2009 an oil tank ship went agro...",October 27 2009 oil tank ship went aground nea...
2826,7603,2002-03-07,"MV Faro I; Cape Florida, FL","Cape Florida, FL",25.6667,-80.133300,NaN,NaN,diesel,NaN,NaN,NaN,NaN,NaN,6500.0,6,"The M/V Faro, a 180 foot freighter grounded 6 ...",MV Faro 180 foot freighter grounded 6 March 20...
2827,7602,2002-02-19,"OSV Luke David; 21nm south of Mobile Bay, AL","21nm south of Mobile Bay, AL",29.8833,-88.033300,NaN,NaN,diesel,NaN,NaN,NaN,NaN,NaN,11300.0,16,At approximately 0830 CST NOAA Hazmat was noti...,approximately 0830 CST NOAA Hazmat notified MS...
2828,7601,2002-02-02,"MV Lorine; S of St. Johns Is, Virgin Islands","S of St. Johns Is, Virgin Islands",18.2667,-64.550000,NaN,NaN,oil,NaN,NaN,NaN,NaN,NaN,NaN,27,Received notification on 1 FEB 02 from GANTSEC...,Received notification 1 FEB 02 GANTSEC OPCEN M...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4430,6204,1968-06-13,"World Glory; 65 miles ENE of Durban, South Africa","65 miles ENE of Durban, South Africa",-29.6333,32.250000,NaN,NaN,Kuwait crude oil,NaN,NaN,NaN,1.0,NaN,14000000.0,6,"At 1500 on June 13, 1968, the World Glory, bo...",1500 June 13 1968 World Glory bound Huelva Spa...
4431,6203,1968-03-07,"General Colocotronis; Eleuthera Island, Bahamas","Eleuthera Island, Bahamas",25.3333,-76.333300,NaN,NaN,"Venezuelan crude oil, diesel fuel",NaN,NaN,NaN,1.0,1.0,1550000.0,6,"On March 7, 1968, the Greek tank vessel Genera...",March 7 1968 Greek tank vessel General Colocot...
4432,6202,1968-03-03,"Ocean Eagle; San Juan, Puerto Rico","San Juan, Puerto Rico",18.4833,-66.166700,NaN,NaN,Venezuelan light crude oil,NaN,NaN,NaN,1.0,NaN,2940000.0,15,"On the morning of March 3, 1968, the tanker Oc...",morning March 3 1968 tanker Ocean Eagle ground...
4433,6201,1967-03-18,"Torrey Canyon; Lands End, England","Lands End, England",50.0500,-4.733330,NaN,NaN,Kuwait crude oil,NaN,NaN,NaN,1.0,1.0,36100000.0,5,"On the morning of March 18, 1967, the T/V Torr...",morning March 18 1967 TV Torrey Canyon ran agr...
4434,6200,1957-03-29,"Tampico Maru; Northern Baja California, about ...","Northern Baja California, about 1 mile north o...",31.3333,-116.467000,NaN,NaN,"diesel oil - approx. 80% heavy distillate, 20%...",NaN,NaN,NaN,NaN,NaN,NaN,5,The Tampico Maru (henceforth Tampico) left Lo...,Tampico Maru henceforth Tampico left Los Angel...

In [34]:
data['threat'].fillna('Unknown', inplace=True)

In [36]:
data['threat'].value_counts()

Oil         2529
Unknown     1340
Chemical     292
Other        274
Name: threat, dtype: int64

In [23]:
data['threat'].value_counts()

Oil         2529
Chemical     292
Other        274
Name: threat, dtype: int64

In [37]:
filtered_data = data[(data['threat'] == 'Oil') | (data['threat'] == 'Chemical')]

In [38]:
filtered_data

,id,open_date,name,location,lat,lon,threat,tags,commodity,measure_skim,measure_shore,measure_bio,measure_disperse,measure_burn,max_ptl_release_gallons,posts,description,preproc
0,10659,2023-09-01,"Crude Oil Spill at Port Manatee in Tampa Bay, FL","St. Petersburg, FL, USA",27.634018,-82.565190,Oil,NaN,Crude,NaN,NaN,NaN,NaN,NaN,3500.0,0,"Late on August 31, 2023, a crude oil spill occ...",Late August 31 2023 crude oil spill occurred P...
1,10660,2023-09-01,Grounded Drug-running Submarine,"Mona Island, PR",18.073605,-67.931855,Oil,NaN,diesel,NaN,NaN,NaN,NaN,NaN,NaN,0,A drug runner sailboat modified to operate as ...,drug runner sailboat modified operate semisubm...
2,10657,2023-08-28,"26-foot Cabin Cruiser Sunk, Bellingham Bay, Be...","Bellingham, WA",48.723710,-122.509100,Oil,NaN,gasoline,NaN,NaN,NaN,NaN,NaN,35.0,0,"On 28-AUG-2023, USCG Sector Puget Sound notifi...",28AUG2023 USCG Sector Puget Sound notified NOA...
4,10658,2023-08-27,"53-foot Motor Yacht Adrift Off Big Sur, CA","off Big Sur, CA",36.028000,-121.867333,Oil,NaN,Diesel,NaN,NaN,NaN,NaN,NaN,800.0,0,"Late Sunday night (27-AUG-2023), USCG Sector S...",Late Sunday night 27AUG2023 USCG Sector San Fr...
5,10655,2023-08-24,"38-foot Fishing Vessel Listing, Funter Bay, An...","Funter Bay, Angoon, AK, USA",58.231056,-134.919000,Oil,NaN,Diesel,NaN,NaN,NaN,NaN,NaN,250.0,0,"On August 25, 2023, the USCG Sector Juneau con...",August 25 2023 USCG Sector Juneau contacted NO...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4425,6209,1970-02-10,Chevron Main Pass Block 41; 11 miles E of the ...,"11 miles E of the Mississippi River delta, Lou...",29.383300,-88.983300,Oil,NaN,crude oil,NaN,NaN,NaN,1.0,NaN,NaN,9,The Chevron Main Pass Block 41C platform caugh...,Chevron Main Pass Block 41C platform caught fi...
4426,6208,1970-02-04,"Arrow; Nova Scotia, Canada","Nova Scotia, Canada",45.466700,-61.100000,Oil,Grounding,Bunker C Oil,NaN,NaN,NaN,1.0,1.0,3470000.0,7,"On February 4, 1970, at 0935, the steam tanker...",February 4 1970 0935 steam tanker Arrow ran ha...
4427,6207,1969-04-30,"Hamilton Trader; Liverpool Bay, England","Liverpool Bay, England",53.500000,3.333330,Oil,Collision,No. 6 Fuel Oil,NaN,NaN,NaN,1.0,NaN,168000.0,6,"Early on the morning of April 30, 1969, the Ha...",Early morning April 30 1969 Hannes Knuppel col...
4428,6206,1969-01-28,"Santa Barbara Well blowout; Santa Barbara, Cal...","Santa Barbara, California",34.166700,-119.750000,Oil,Wellhead,California crude oil,NaN,NaN,NaN,1.0,NaN,4200000.0,8,"On January 28, 1969, the Union Oil Company wel...",January 28 1969 Union Oil Company well number ...
4429,6205,1968-12-13,"Witwater; Galeta Island, Canal Zone, Panama","Galeta Island, Canal Zone, Panama",9.583330,-80.666700,Oil,Collision,"Diesel, Bunker C",NaN,NaN,NaN,NaN,1.0,588000.0,6,"On December 13, 1968, the oil tanker Witwater ...",December 13 1968 oil tanker Witwater broke hea...

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Sample preprocessed text data
preprocessed_text = filtered_data.preproc

# Initialize the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer()

# Fit and transform the preprocessed text data
tfidf_matrix = tfidf_vectorizer.fit_transform(preprocessed_text)

# Get the feature names (words) used for the columns in the TF-IDF matrix
feature_names = tfidf_vectorizer.get_feature_names_out()

# Convert the TF-IDF matrix to a dense array for better readability (optional)
tfidf_matrix_dense = tfidf_matrix.toarray()

# Print the feature names and TF-IDF matrix
print("Feature Names (Words):")
print(feature_names)
print("\nTF-IDF Matrix:")
print(tfidf_matrix_dense)

Feature Names (Words):
['00' '000' '0000' ... 'zug' 'zulu' 'zuma']

TF-IDF Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

In [40]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Split the data into training and testing sets
X = tfidf_matrix_dense  # TF-IDF matrix
y = filtered_data['threat']  # Target labels
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the classifier
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = classifier.predict(X_test)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print a classification report with precision, recall, and F1-score
report = classification_report(y_test, y_pred)
print(report)

Accuracy: 0.90
              precision    recall  f1-score   support

    Chemical       0.00      0.00      0.00        58
         Oil       0.90      1.00      0.95       507

    accuracy                           0.90       565
   macro avg       0.45      0.50      0.47       565
weighted avg       0.81      0.90      0.85       565

/packages/envs/scicomp/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/packages/envs/scicomp/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/packages/envs/scicomp/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [42]:
%pip install -U imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting imbalanced-learn
  Downloading imbalanced_learn-0.11.0-py3-none-any.whl (235 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.6/235.6 kB 6.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17.3 in ./.local/lib/python3.11/site-packages (from imbalanced-learn) (1.23.0)
Requirement already satisfied: scipy>=1.5.0 in /packages/envs/scicomp/lib/python3.11/site-packages (from imbalanced-learn) (1.9.3)
Requirement already satisfied: scikit-learn>=1.0.2 in /packages/envs/scicomp/lib/python3.11/site-packages (from imbalanced-learn) (1.2.2)
Requirement already satisfied: joblib>=1.1.1 in /packages/envs/scicomp/lib/python3.11/site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /packages/envs/scicomp/lib/python3.11/site-packages (from imbalanced-learn) (3.1.0)
Installing collected packages: imbalanced-learn
Successfully installed imbalanced-learn-0.11.0
Note: you may need to restart the kernel to use updated packages.

In [43]:
from imblearn.over_sampling import SMOTE
from collections import Counter

# Check the class distribution before oversampling
print("Class distribution before oversampling:", Counter(y))

# Create an instance of SMOTE
smote = SMOTE(random_state=42)

# Apply SMOTE to generate synthetic samples
X_resampled, y_resampled = smote.fit_resample(X, y)

# Check the class distribution after oversampling
print("Class distribution after oversampling:", Counter(y_resampled))

Class distribution before oversampling: Counter({'Oil': 2529, 'Chemical': 292})
Class distribution after oversampling: Counter({'Oil': 2529, 'Chemical': 2529})

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Initialize and train the classifier
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Make predictions on the test data
y_pred = classifier.predict(X_test)

# Calculate and print the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

# Print a classification report with precision, recall, and F1-score
report = classification_report(y_test, y_pred)
print(report)

Accuracy: 0.98
              precision    recall  f1-score   support

    Chemical       0.97      1.00      0.98       493
         Oil       1.00      0.97      0.98       519

    accuracy                           0.98      1012
   macro avg       0.98      0.98      0.98      1012
weighted avg       0.98      0.98      0.98      1012